CREATE SCHEMA IF NOT exists rubus
    AUTHORIZATION coleo;

ALTER SCHEMA rubus OWNER TO coleo;

REVOKE ALL ON SCHEMA RUBUS FROM PUBLIC;
REVOKE ALL ON SCHEMA RUBUS FROM read_only_public;

GRANT ALL ON SCHEMA rubus TO coleo;
GRANT USAGE ON SCHEMA rubus TO read_only_all;
GRANT USAGE ON SCHEMA rubus TO read_write_all;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus REVOKE ALL ON TABLES FROM read_only_public;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus REVOKE ALL ON TABLES FROM read_only_public;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus REVOKE ALL ON TABLES FROM read_only_public;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus REVOKE ALL ON TABLES FROM read_only_public;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus REVOKE ALL ON TABLES FROM read_only_public;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus REVOKE ALL ON TABLES FROM read_only_public;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus REVOKE ALL ON TABLES FROM read_only_public;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT SELECT ON TABLES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT SELECT ON TABLES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT SELECT ON TABLES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT SELECT ON TABLES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT SELECT ON TABLES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT SELECT ON TABLES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT SELECT ON TABLES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_only_all;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_only_all;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER merb2202 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER vbeaure IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER cabw2601 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER camv2202 IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER glaroc IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;