-- Schema rubus --
CREATE SCHEMA IF NOT exists rubus
    AUTHORIZATION coleo;

--- Revoke and grants
REVOKE ALL ON SCHEMA RUBUS FROM PUBLIC;
REVOKE ALL ON SCHEMA RUBUS FROM read_only_public;

GRANT ALL ON SCHEMA rubus TO coleo;
GRANT USAGE ON SCHEMA rubus TO read_only_all, read_write_all;

--- Alter default privileges
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT TRUNCATE, INSERT, SELECT, TRIGGER, UPDATE, REFERENCES ON TABLES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO read_write_all;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO read_write_all;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT ALL ON TABLES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT USAGE ON SEQUENCES TO coleo;
ALTER DEFAULT PRIVILEGES FOR USER coleo IN SCHEMA rubus GRANT EXECUTE ON FUNCTIONS TO coleo;